### ISSUE TITLE
Filter for platform compatibility

### ISSUE THREAD

**Issue by peggyrayzis** [react-community/native-directory#48]
Right now, you can sort by compatibility, but that isn't super useful if you're looking to isolate only web compatible libraries. I think filtering by platform would be much more intuitive - what do you think?

**Comment by jimmylee** [comment]
**Makes a ton of sense**. I just haven't gotten around to it yet, but this has been requested numerous times before.

I'll make it a priority to resolve this issue in the next couple of days. I need to knock out some other work beforehand.

Thanks @peggyrayzis 🙌

**Comment by peggyrayzis** [comment]
Awesome! 😀 I'm planning on featuring native.directory to showcase web compatible RN libs in my talk at ReactNext on Sep 10. If you're able to get to it by then, that would be super cool but otherwise no rush. Thanks!

**Comment by jimmylee** [comment]
Hey @peggyrayzis some changes have landed on https://native.directory 

![native](https://user-images.githubusercontent.com/310223/30014540-a8172c7a-9101-11e7-84d2-2de57497d21b.png)

- Compatibility is now visible at the top of the page. When a user clicks a link, the control toggles between `Optional` and `Required`. Because of this, a user is able to see RN libraries that must be compatible with one of the four sub categories: `ios`, `android`, `web`, `expo`.
- Example page queries:
    - https://native.directory/?ios=true&android=true
    - https://native.directory/?web=true
    - https://native.directory/?search=webgl&web=true
- You can also query this information with JSON:
    - https://native.directory/stars/react?web=true&json=true
    - https://native.directory?ios=true&android=true&json=true
- All possibilities:
    - `https://native.directory/<:order>/<:topic>/?search=<string>&json=<bool>&web=<bool>&expo=<bool>&ios=<bool>&android<bool>`
- CURL:
    - `curl -X GET 'https://native.directory?web=true&json=true'`

I hope this help you out with your presentation! So excited that you're going to showcase web compatible RN libs.

Let me know if I can help in any other way! 😎

**Comment by peggyrayzis** [comment]
Wow @jimmylee this looks amazing!! I can't thank you enough for pushing out the changes so quickly. Can't wait to feature this in my presentation 🎉
