### ISSUE TITLE
Way to add topics

### ISSUE THREAD

**Issue by deadcoder0904** [react-community/native-directory#63]
I might have overlooked but couldn't find a way to add more topics. 

Of course u can review it later if I've added some wrong topics. Bcz I'm finding some really awesome 😍  libraries which aren't there in `native.directory` so want to add them & I can later use it for my other projects like I use `npm` 😝 

Also a PR from me got merged before but results aren't visible on the website. The component is `react-native-bouncy-drawer` & when I search `bouncy` or `drawer` nothing gets returned 🤔 

Can someone explain whats the case ❓

**Comment by deadcoder0904** [comment]
& plzzz automate this shit after merging. Manually it would take a lot of time, resources & efforts. 

Bcz this is pure gold 🥇  for React Native

**Comment by kelset** [comment]
The topics are parsed from GitHub. And I'm not sure what's the frequency on which the parsing of Github info get parsed.

**Comment by jimmylee** [comment]
Hey @deadcoder0904 thanks for being a fan!

Right now, the updating is done manually via a commit, this is because the requests to GitHub in the pipeline sometimes fail while I'm scrapping data, and I haven't had the time to really sit down and think of a cron-job-like solution thats fail tolerant.

I know people may not like this, hope you guys can bear with me :) Thanks.

**Comment by deadcoder0904** [comment]
No problem. Thanks for creating it. Its like `npm` for React Native. Looks like I've got u a tagline 😉

**Comment by jimmylee** [comment]
https://native.directory?search=bouncy
https://native.directory?serach=bouncy&json=true

Enjoy 😎
